const { userTypes, config } = require('../config');
const jwt = require('jsonwebtoken');
const {
  TokenExpiredError,
  JsonWebTokenError,
  TokenNotBefore,
  GeneralTokenError,
} = require('../errors');

/**
 * @class AuthTokenService
 * @classdesc
 * Singleton service for handling JSON Web Token (JWT) operations in the application.
 * Provides methods for generating token payloads, creating access and refresh tokens,
 * and verifying tokens securely.
 *
 * This service ensures that JWT errors are mapped to application-level errors
 * without exposing sensitive information to clients, enhancing security.
 *
 * @example
 * const authService = require('./services/authTokenService');
 * const payload = authService.generatePayload(userTypes.USER_ADMIN, '12345', Date.now());
 * const accessToken = authService.generateAccessToken(payload);
 * const decoded = authService.verifyAccessToken(accessToken);
 */
class authTokenServiceSupport {
  /**
   * Initializes the singleton instance of AuthTokenService.
   * @constructor
   */
  constructor() {
    if (authTokenServiceSupport.instance == null) {
      authTokenServiceSupport.instance = this;
      Object.freeze(this);
    }
    return authTokenServiceSupport.instance;
  }

  /**
   * Generates a structured payload for JWT tokens.
   *
   * @param {string} userType - The type of user (use values from `userTypes`).
   * @param {string|number} id - Unique identifier of the user.
   * @param {number} expiresTimestamp - Expiration timestamp (optional metadata).
   * @param {number} [priority=0] - Optional priority level for internal usage.
   * @param {object} [other={}] - Optional additional metadata to include in payload.
   * @returns {object} A structured payload object suitable for signing JWT tokens.
   *
   * @example
   * const payload = authTokenService.generatePayload(userTypes.USER_STUDENT, 'abc123', Date.now());
   */
  generatePayload(userType, id, expiresTimestamp, priority = 0, other = {}) {
    return {
      userType: userType,
      id: id,
      priority: priority,
      expiresTimestamp: expiresTimestamp,
      other: other,
    };
  }

  /**
   * @private
   * @method #generate
   * @description
   * Signs a payload into a JWT token using the provided secret and options.
   * This is a low-level utility method for generating tokens. Typically,
   * `generateAccessToken` and `generateRefreshToken` should be used instead
   * for standard token generation.
   *
   * @param {object} payload - The payload object to encode into the JWT.
   * @param {string} secret - Secret key used to sign the token.
   * @param {object} [options={}] - Optional signing options (see `jsonwebtoken` documentation).
   *   Common options include:
   *   - `expiresIn` (string|number): Token expiration time.
   *   - `algorithm` (string): Signing algorithm (e.g., 'HS256').
   *
   * @returns {string} The signed JWT token.
   *
   */
  #generate(payload, secret, options) {
    return jwt.sign(payload, secret, options);
  }

  /**
   * Generates a signed JWT access token from a payload.
   *
   * @param {object} payload - JWT payload object generated by `generatePayload()`.
   * @returns {string} Signed JWT access token.
   *
   * @example
   * const accessToken = authTokenService.generateAccessToken(payload);
   */
  generateAccessToken(payload) {
    return this.#generate(payload, config.ACCESS_TOKEN_SECRET, {
      expiresIn: config.ACCESS_TOKEN_TTL,
    });
  }

  /**
   * Generates a signed JWT refresh token from a payload.
   *
   * @param {object} payload - JWT payload object generated by `generatePayload()`.
   * @returns {string} Signed JWT refresh token.
   *
   * @example
   * const refreshToken = authTokenService.generateRefreshToken(payload);
   */
  generateRefreshToken(payload) {
    return this.#generate(payload, config.REFRESH_TOKEN_SECRET, {
      expiresIn: config.REFRESH_TOKEN_TTL,
    });
  }

  /**
   * @private
   * Verifies a JWT token against a secret key.
   * Maps JWT library errors to application-level errors securely without exposing
   * sensitive internal details to the client.
   *
   * @param {string} token - JWT token to verify.
   * @param {string} secret - Secret key for verification (access or refresh token secret).
   * @throws {TokenExpiredError|JsonWebTokenError|TokenNotBefore|GeneralTokenError}
   * @returns {object} Decoded JWT payload if verification succeeds.
   */
  #verify(token, secret) {
    try {
      return jwt.verify(token, secret);
    } catch (error) {
      switch (error.name) {
        case 'TokenExpiredError':
          throw new TokenExpiredError();
        case 'JsonWebTokenError':
          throw new JsonWebTokenError();
        case 'NotBeforeError':
          throw new TokenNotBefore();
        default:
          throw new GeneralTokenError();
      }
    }
  }

  /**
   * Verifies a JWT access token securely.
   *
   * @param {string} token - JWT access token to verify.
   * @throws {TokenExpiredError|JsonWebTokenError|TokenNotBefore|GeneralTokenError}
   * @returns {object} Decoded JWT payload if verification succeeds.
   *
   * @example
   * const decoded = authTokenService.verifyAccessToken(accessToken);
   */
  verifyAccessToken(token) {
    return this.#verify(token, config.ACCESS_TOKEN_SECRET);
  }

  /**
   * Verifies a JWT refresh token securely.
   *
   * @param {string} token - JWT refresh token to verify.
   * @throws {TokenExpiredError|JsonWebTokenError|TokenNotBefore|GeneralTokenError}
   * @returns {object} Decoded JWT payload if verification succeeds.
   *
   * @example
   * const decoded = authTokenService.verifyRefreshToken(refreshToken);
   */
  verifyRefreshToken(token) {
    return this.#verify(token, config.REFRESH_TOKEN_SECRET);
  }
}

module.exports = new authTokenServiceSupport();
